### PR TITLE
Clean up scripts

### PR DESCRIPTION
**Pull request by szepeviktor**
- safety
- simplicity
- readability
- uniformity

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you.

**Comment by piraz** [comment]
Hey @szepeviktor can we move from python 3.5?

**Comment by szepeviktor** [comment]
Yes.

**Comment by piraz** [comment]
I'm getting the ec ticket from manuale also implemented here.

This one: https://github.com/veeti/manuale/issues/14#

Sorry about the inactivity. Was a crazy year personally, everything went good but not time to open source things.

I'll be back and providing real automation to the project.

**Pull request merged**
