### PR TITLE
Merge piraz/automatoes

### PR DESCRIPTION
**Pull request by szepeviktor**
@piraz Which is the "main" repo?

- candango/automatoes ?
- piraz/automatoes ?

You can develop in a new branch in candango/automatoes!

### CODE REVIEW

**Comment by piraz** [comment]
Main is candango. I do my things on mine than push to candango.

I'm still working ...

**Comment by szepeviktor** [comment]
Okay.

**Comment by piraz** [comment]
I seems like it is working fine, I'll just tweak a little legacy readme and the warning is gone.

**Comment by szepeviktor** [comment]
Thank you for your work.
100% coverage does not hurt :)

**Pull request merged**
